---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: worker1
      containers:
      - name: nginx
        image: orangius/app_m2ssi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80